package com.keynor.rpg.application.dto;

import com.keynor.rpg.domain.model.PlayableCharacter;

/**
 * Flat, non-pool attributes. Stamina Pool, Mental Health Pool, Memory Pool, Mana Pool, and Chi
 * Pool moved out to {@link PoolAttributesResponse} — each now carries a separate total/current
 * pair instead of a single flat value.
 */
public record AttributesResponse(double pushStrength, double legDrive, double gripStrength, double liftStrength,
                                  double swingPower, double grapplingSelfLifting, double speed,
                                  double movementSpeed, double fatigueResistance,
                                  double staminaRecovery, double softTissueDurability, double boneDurability,
                                  double sight, double hearing,
                                  double smell, double evasion, double acrobatics, double meleeAccuracy, double aim,
                                  double reasoning, double shortMemory,
                                  double will, double balance, double stressResistance, double angerResistance,
                                  double fearResistance, double painThreshold, double poisonResistance,
                                  double diseaseResistance, double bleedingResistance, double thermalResistance,
                                  double breathOutput, double dehydrationResistance, double starvationResistance,
                                  double foodPoisoningAlcoholResistance, double fatGainRate, double muscleGainRate,
                                  double intimidation, double diplomacy, double enfactuation, double command,
                                  double arcaneOutput, double mediunity,
                                  double selfConcern, double friendshipConcern, double orderConcern,
                                  double freedomConcern, double patriotismConcern, double spiritualConcern,
                                  double philosophyConcern, double academicConcern, double environmentalismConcern,
                                  double moralityConcern, double traditionalismConcern, double justiceConcern,
                                  double progressConcern, double peaceConcern,
                                  double survivalSkills, double animalCaring, double manipulation,
                                  double behaviorReading, double discretion, double bluffing, double faith,
                                  double illusionResistance, double creativity, double analysis,
                                  double closeCombat, double lowRangeCombat, double longRangeCombat,
                                  double psyquismOutput, double psyquismDefense, double charmResistance,
                                  double concentration, double purity, double reactionSpeed, double hiding,
                                  double sneaking, double alchemy, double machineHandling, double performance,
                                  double sciencePractice, double healing, double hackingAndPrograming) {

    public static AttributesResponse from(PlayableCharacter character) {
        return new AttributesResponse(
                character.getPushStrength(),
                character.getLegDrive(),
                character.getGripStrength(),
                character.getLiftStrength(),
                character.getSwingPower(),
                character.getGrapplingSelfLifting(),
                character.getSpeed(),
                character.getMovementSpeed(),
                character.getFatigueResistance(),
                character.getStaminaRecovery(),
                character.getSoftTissueDurability(),
                character.getBoneDurability(),
                character.getSight(),
                character.getHearing(),
                character.getSmell(),
                character.getEvasion(),
                character.getAcrobatics(),
                character.getMeleeAccuracy(),
                character.getAim(),
                character.getReasoning(),
                character.getShortMemory(),
                character.getWill(),
                character.getBalance(),
                character.getStressResistance(),
                character.getAngerResistance(),
                character.getFearResistance(),
                character.getPainThreshold(),
                character.getPoisonResistance(),
                character.getDiseaseResistance(),
                character.getBleedingResistance(),
                character.getThermalResistance(),
                character.getBreathOutput(),
                character.getDehydrationResistance(),
                character.getStarvationResistance(),
                character.getFoodPoisoningAlcoholResistance(),
                character.getFatGainRate(),
                character.getMuscleGainRate(),
                character.getIntimidation(),
                character.getDiplomacy(),
                character.getEnfactuation(),
                character.getCommand(),
                character.getArcaneOutput(),
                character.getMediunity(),
                character.getSelfConcern(),
                character.getFriendshipConcern(),
                character.getOrderConcern(),
                character.getFreedomConcern(),
                character.getPatriotismConcern(),
                character.getSpiritualConcern(),
                character.getPhilosophyConcern(),
                character.getAcademicConcern(),
                character.getEnvironmentalismConcern(),
                character.getMoralityConcern(),
                character.getTraditionalismConcern(),
                character.getJusticeConcern(),
                character.getProgressConcern(),
                character.getPeaceConcern(),
                character.getSurvivalSkills(),
                character.getAnimalCaring(),
                character.getManipulation(),
                character.getBehaviorReading(),
                character.getDiscretion(),
                character.getBluffing(),
                character.getFaith(),
                character.getIllusionResistance(),
                character.getCreativity(),
                character.getAnalysis(),
                character.getCloseCombat(),
                character.getLowRangeCombat(),
                character.getLongRangeCombat(),
                character.getPsyquismOutput(),
                character.getPsyquismDefense(),
                character.getCharmResistance(),
                character.getConcentration(),
                character.getPurity(),
                character.getReactionSpeed(),
                character.getHiding(),
                character.getSneaking(),
                character.getAlchemy(),
                character.getMachineHandling(),
                character.getPerformance(),
                character.getSciencePractice(),
                character.getHealing(),
                character.getHackingAndPrograming());
    }
}
